services:
  web:
    build: ./App
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - backend

  celery:
    build: ./App
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    driver: bridge
